### ISSUE TITLE
Average Demand Interval (ADI) function in classification() is wrong!

### ISSUE THREAD

**Issue by muhalitas** [Valdecy/Forecast_Intermittent_Demand#1]
According to intermittent forecasting, ADI- Average Demand Interval is calculated as Total Number of Periods/ Total Number of Demand Periods. 

But your function sums up the demand which is completely wrong.

**Comment by Valdecy** [comment]
Thank you very much for highlighting the error! We recommend updating to version 1.4.3, which includes the necessary corrections in the code.

**Comment by Valdecy** [comment]
Thank you very much for highlighting the error! We recommend updating to version 1.4.3, which includes the necessary corrections in the code.
